const keyTable = [
  { key: { en: '`', ru: 'ё' }, shift: { en: '~', ru: 'Ё' }, code: 'Backquote' },
  { key: { en: '1', ru: '1' }, shift: { en: '!', ru: '!' }, code: 'Digit1' },
  { key: { en: '2', ru: '2' }, shift: { en: '@', ru: '"' }, code: 'Digit2' },
  { key: { en: '3', ru: '3' }, shift: { en: '#', ru: '№' }, code: 'Digit3' },
  { key: { en: '4', ru: '4' }, shift: { en: '$', ru: ';' }, code: 'Digit4' },
  { key: { en: '5', ru: '5' }, shift: { en: '%', ru: '%' }, code: 'Digit5' },
  { key: { en: '6', ru: '6' }, shift: { en: '^', ru: ':' }, code: 'Digit6' },
  { key: { en: '7', ru: '7' }, shift: { en: '&', ru: '?' }, code: 'Digit7' },
  { key: { en: '8', ru: '8' }, shift: { en: '*', ru: '*' }, code: 'Digit8' },
  { key: { en: '9', ru: '9' }, shift: { en: '(', ru: '(' }, code: 'Digit9' },
  { key: { en: '0', ru: '0' }, shift: { en: ')', ru: ')' }, code: 'Digit0' },
  { key: { en: '-', ru: '-' }, shift: { en: '_', ru: '_' }, code: 'Minus' },
  { key: { en: '=', ru: '=' }, shift: { en: '+', ru: '+' }, code: 'Equal' },
  {
    key: 'backspace',
    code: 'Backspace',
    specialKey: true,
    width: 'long1',
  },
  {
    key: 'tab',
    code: 'Tab',
    specialKey: true,
    width: 'medium',
  },
  { key: { en: 'q', ru: 'й' }, shift: { en: 'Q', ru: 'Й' }, code: 'KeyQ' },
  { key: { en: 'w', ru: 'ц' }, shift: { en: 'W', ru: 'Ц' }, code: 'KeyW' },
  { key: { en: 'e', ru: 'у' }, shift: { en: 'E', ru: 'У' }, code: 'KeyE' },
  { key: { en: 'r', ru: 'к' }, shift: { en: 'R', ru: 'К' }, code: 'KeyR' },
  { key: { en: 't', ru: 'е' }, shift: { en: 'T', ru: 'Е' }, code: 'KeyT' },
  { key: { en: 'y', ru: 'н' }, shift: { en: 'Y', ru: 'Н' }, code: 'KeyY' },
  { key: { en: 'u', ru: 'г' }, shift: { en: 'U', ru: 'Г' }, code: 'KeyU' },
  { key: { en: 'i', ru: 'ш' }, shift: { en: 'I', ru: 'Ш' }, code: 'KeyI' },
  { key: { en: 'o', ru: 'щ' }, shift: { en: 'O', ru: 'Щ' }, code: 'KeyO' },
  { key: { en: 'p', ru: 'з' }, shift: { en: 'P', ru: 'З' }, code: 'KeyP' },
  {
    key: { en: '[', ru: 'х' },
    shift: { en: '{', ru: 'Х' },
    code: 'BracketLeft',
  },
  {
    key: { en: ']', ru: 'ъ' },
    shift: { en: '}', ru: 'Ъ' },
    code: 'BracketRight',
  },
  {
    key: { en: '\\', ru: '\\' },
    shift: { en: '|', ru: '|' },
    code: 'Backslash',
  },
  { key: 'del', code: 'Delete', specialKey: true },
  {
    key: 'capslock',
    code: 'CapsLock',
    specialKey: true,
    width: 'long',
  },
  { key: { en: 'a', ru: 'ф' }, shift: { en: 'A', ru: 'Ф' }, code: 'KeyA' },
  { key: { en: 's', ru: 'ы' }, shift: { en: 'S', ru: 'Ы' }, code: 'KeyS' },
  { key: { en: 'd', ru: 'в' }, shift: { en: 'D', ru: 'В' }, code: 'KeyD' },
  { key: { en: 'f', ru: 'а' }, shift: { en: 'F', ru: 'А' }, code: 'KeyF' },
  { key: { en: 'g', ru: 'п' }, shift: { en: 'G', ru: 'П' }, code: 'KeyG' },
  { key: { en: 'h', ru: 'р' }, shift: { en: 'H', ru: 'Р' }, code: 'KeyH' },
  { key: { en: 'j', ru: 'о' }, shift: { en: 'J', ru: 'О' }, code: 'KeyJ' },
  { key: { en: 'k', ru: 'л' }, shift: { en: 'K', ru: 'Л' }, code: 'KeyK' },
  { key: { en: 'l', ru: 'д' }, shift: { en: 'L', ru: 'Д' }, code: 'KeyL' },
  { key: { en: ';', ru: 'ж' }, shift: { en: ':', ru: 'Ж' }, code: 'Semicolon' },
  { key: { en: "'", ru: 'э' }, shift: { en: '"', ru: 'Э' }, code: 'Quote' },
  {
    key: 'enter',
    code: 'Enter',
    specialKey: true,
    width: 'long',
  },
  {
    key: 'shift',
    code: 'ShiftLeft',
    specialKey: true,
    width: 'long',
  },
  { key: { ru: 'я', en: 'z' }, shift: { ru: 'Я', en: 'Z' }, code: 'KeyZ' },
  { key: { ru: 'ч', en: 'x' }, shift: { ru: 'Ч', en: 'X' }, code: 'KeyX' },
  { key: { ru: 'с', en: 'c' }, shift: { ru: 'С', en: 'C' }, code: 'KeyC' },
  { key: { ru: 'м', en: 'v' }, shift: { ru: 'М', en: 'V' }, code: 'KeyV' },
  { key: { ru: 'и', en: 'b' }, shift: { ru: 'И', en: 'B' }, code: 'KeyB' },
  { key: { ru: 'т', en: 'n' }, shift: { ru: 'Т', en: 'N' }, code: 'KeyN' },
  { key: { ru: 'ь', en: 'm' }, shift: { ru: 'Ь', en: 'M' }, code: 'KeyM' },
  { key: { ru: 'б', en: ',' }, shift: { ru: 'Б', en: '<' }, code: 'Comma' },
  { key: { ru: 'ю', en: '.' }, shift: { ru: 'Ю', en: '>' }, code: 'Period' },
  { key: { ru: '.', en: '/' }, shift: { ru: ',', en: '?' }, code: 'Slash' },
  { key: '▲', code: 'ArrowUp', specialKey: true },
  {
    key: 'shift',
    code: 'ShiftRight',
    specialKey: true,
    width: 'long',
  },
  { key: 'ctrl', code: 'ControlLeft', specialKey: true },
  { key: 'win', code: 'OSLeft', specialKey: true },
  { key: 'alt', code: 'AltLeft', specialKey: true },
  { key: ' ', code: 'Space', width: 'long3' },
  { key: 'alt', code: 'AltRight', specialKey: true },
  { key: 'ctrl', code: 'ControlRight', specialKey: true },
  { key: '◄', code: 'ArrowLeft', specialKey: true },
  { key: '▼', code: 'ArrowDown', specialKey: true },
  { key: '►', code: 'ArrowRight', specialKey: true },
  {
    key: { en: 'en', ru: 'ru' },
    shift: { en: 'en', ru: 'ru' },
    code: 'Lang',
    specialKey: true,
    width: 'long2',
  },
];

export default keyTable;
